# cloudinit.sh — run-time credential generation and the NoCloud seed for the
# booted-VM harness (#67).
#
# This is a SOURCED library, not a program: it is committed non-executable and
# is never invoked as a command. Source it from a bash host-side script:
#
#     . test/vm/lib/cloudinit.sh
#     create_run_workspace "$RUNNER_TEMP/vm-boot"
#     create_seed debian "$VM_WORKSPACE"
#     # ... then boot "$VM_SEED_ISO" with the credentials in "$VM_WORKSPACE"
#
# create_seed is called directly and never through a command substitution: it
# exports the workspace paths its callers need — VM_SSH_KEY, VM_CREDS_ENV and
# VM_SEED_ISO — and a subshell would discard every one of them.
#
# Nothing in this file is a credential. Every credential the harness uses —
# the ed25519 keypair, the administrator's password and root's password — is
# generated HERE, on the host, at run time, into the 0700 run workspace, and
# lives only there: it is never committed, never printed, never uploaded and
# never baked into an image. No guest-side command generates any credential.
#
# The emitted user-data declares exactly ONE login account, the administrator.
# root gets no authorized key and SSH root login is not enabled: stock cloud
# images restrict it, enabling it would make the guest less stock, and the
# harness needs root's password to be set and later removed under the test's
# control. Everything that needs privilege escalates instead, which is why the
# account carries a NOPASSWD grant — SSH commands are non-interactive with no
# TTY, so an escalation that prompted would hang forever.
#
# shellcheck shell=bash

set -euo pipefail

# CLOUDINIT_ADMIN_USER is the single guest login account the seed declares.
CLOUDINIT_ADMIN_USER="${CLOUDINIT_ADMIN_USER:-pilotadmin}"

cloudinit_log() {
    printf 'cloudinit: %s\n' "$*" >&2
}

cloudinit_fail() {
    printf 'cloudinit: %s\n' "$*" >&2
    exit 1
}

# create_run_workspace <dir> creates the per-run workspace with mode 0700 and
# exports it as VM_WORKSPACE. Everything generated by this harness — the
# keypair, creds.env, the seed and the overlay disk — lives under it.
create_run_workspace() {
    if [ "$#" -ne 1 ]; then
        cloudinit_fail "usage: create_run_workspace <dir>"
    fi

    mkdir -p "$1"
    chmod 0700 "$1"

    VM_WORKSPACE="$(cd "$1" && pwd)"
    export VM_WORKSPACE
    cloudinit_log "run workspace $VM_WORKSPACE (mode 0700)"
}

# generate_password prints one freshly generated password on standard output.
# Tracing is disabled first and deliberately left off for the rest of the
# shell, so no credential can ever reach the job log through xtrace. The
# alphabet is restricted to unreserved characters so the value survives
# creds.env, YAML and an HTTP form body unquoted.
generate_password() {
    set +x

    local raw=""
    if command -v openssl >/dev/null 2>&1; then
        raw="$(openssl rand -base64 48 | LC_ALL=C tr -dc 'A-Za-z0-9' || true)"
    fi

    if [ "${#raw}" -lt 24 ]; then
        raw="$(LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom 2>/dev/null | head -c 96 || true)"
    fi

    if [ "${#raw}" -lt 24 ]; then
        cloudinit_fail "no openssl and /dev/urandom yielded too little to build a credential"
    fi

    printf '%s\n' "${raw:0:24}"
}

# generate_credentials <workspace> generates, into that workspace and nowhere
# else, the ed25519 keypair and both generated passwords, and writes
# creds.env (PH_ADMIN_USER, PH_ADMIN_PASSWORD, PH_ROOT_PASSWORD) beside them.
# VM_SSH_KEY and VM_CREDS_ENV are exported for ssh.sh and the orchestrator.
generate_credentials() {
    set +x

    if [ "$#" -ne 1 ]; then
        cloudinit_fail "usage: generate_credentials <workspace>"
    fi

    local workspace="$1"
    [ -d "$workspace" ] || cloudinit_fail "workspace does not exist: $workspace"

    VM_SSH_KEY="$workspace/id_ed25519"
    VM_CREDS_ENV="$workspace/creds.env"
    export VM_SSH_KEY VM_CREDS_ENV

    rm -f "$VM_SSH_KEY" "$VM_SSH_KEY.pub"
    ssh-keygen -q -t ed25519 -N '' -C 'pilothouse-vm-boot' -f "$VM_SSH_KEY"
    chmod 0600 "$VM_SSH_KEY"

    local admin_password root_password
    admin_password="$(generate_password)"
    root_password="$(generate_password)"

    # The umask is scoped to a subshell so the restrictive mode applies to the
    # file being written and nothing else in the caller's shell; the explicit
    # chmod is the guarantee.
    (
        umask 0077
        cat >"$VM_CREDS_ENV" <<EOF
PH_ADMIN_USER=$CLOUDINIT_ADMIN_USER
PH_ADMIN_PASSWORD=$admin_password
PH_ROOT_PASSWORD=$root_password
EOF
    )
    chmod 0600 "$VM_CREDS_ENV"

    cloudinit_log "generated an ed25519 keypair and two passwords in $workspace"
}

# admin_group_for_family prints the administrator group the family's package
# declares: `sudo` on Debian, `wheel` on Fedora. That single token is the main
# difference between the two unit files, so it is a per-family branch here and
# never a default.
admin_group_for_family() {
    case "$1" in
        debian) printf '%s\n' 'sudo' ;;
        fedora) printf '%s\n' 'wheel' ;;
        *) cloudinit_fail "unknown family '$1': expected debian or fedora" ;;
    esac
}

# write_cloud_init_seed <family> <workspace> emits the NoCloud meta-data and
# user-data into <workspace>/seed. It reads the generated credentials back out
# of the workspace; generate_credentials must have run first.
write_cloud_init_seed() {
    set +x

    if [ "$#" -ne 2 ]; then
        cloudinit_fail "usage: write_cloud_init_seed <family> <workspace>"
    fi

    local family="$1" workspace="$2"
    local group
    group="$(admin_group_for_family "$family")"

    local creds="$workspace/creds.env"
    [ -f "$creds" ] || cloudinit_fail "credentials not generated yet: $creds"
    [ -f "$workspace/id_ed25519.pub" ] || cloudinit_fail "no public key in $workspace"

    # shellcheck disable=SC1090,SC1091 # generated at run time by generate_credentials
    . "$creds"

    local pubkey
    pubkey="$(cat "$workspace/id_ed25519.pub")"

    local seed_dir="$workspace/seed"
    mkdir -p "$seed_dir"
    chmod 0700 "$seed_dir"

    cat >"$seed_dir/meta-data" <<EOF
instance-id: pilothouse-vm-boot-$family
local-hostname: pilothouse-$family
EOF

    # The heredoc below is the seed template. Every credential in it is a shell
    # variable expansion of a value generated moments ago in this workspace;
    # there is no literal here and there must never be one. Note what is
    # absent as much as what is present: root gets no authorized key, no
    # sshd directive is written, and password authentication over SSH stays
    # off — the one identity is the key generated above.
    (
        umask 0077
        cat >"$seed_dir/user-data" <<EOF
#cloud-config
disable_root: true
ssh_pwauth: false

users:
  - name: $PH_ADMIN_USER
    groups: [$group]
    shell: /bin/bash
    lock_passwd: false
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - $pubkey

chpasswd:
  expire: false
  users:
    - name: $PH_ADMIN_USER
      password: $PH_ADMIN_PASSWORD
      type: text
    - name: root
      password: $PH_ROOT_PASSWORD
      type: text

write_files:
  - path: /etc/systemd/journald.conf.d/99-console.conf
    owner: 'root:root'
    permissions: '0644'
    content: |
      [Journal]
      ForwardToConsole=yes
      MaxLevelConsole=info
      TTYPath=/dev/ttyS0

runcmd:
  - [systemctl, restart, systemd-journald]

output: {all: '| tee -a /dev/console'}
EOF
    )
    chmod 0600 "$seed_dir/user-data"

    cloudinit_log "wrote a NoCloud seed for $family (administrator group $group)"
}

# build_seed_iso <workspace> packs the seed directory into a CIDATA volume and
# prints its path.
build_seed_iso() {
    if [ "$#" -ne 1 ]; then
        cloudinit_fail "usage: build_seed_iso <workspace>"
    fi

    local workspace="$1"
    local seed_dir="$workspace/seed"
    local iso="$workspace/seed.iso"

    [ -f "$seed_dir/user-data" ] || cloudinit_fail "no user-data in $seed_dir"
    rm -f "$iso"

    local maker=""
    local candidate
    for candidate in xorrisofs genisoimage mkisofs; do
        if command -v "$candidate" >/dev/null 2>&1; then
            maker="$candidate"
            break
        fi
    done

    [ -n "$maker" ] || cloudinit_fail "no ISO writer found: install xorriso, genisoimage or mkisofs"

    "$maker" -quiet -output "$iso" -volid cidata -joliet -rock \
        "$seed_dir/user-data" "$seed_dir/meta-data" >/dev/null

    chmod 0600 "$iso"
    printf '%s\n' "$iso"
}

# create_seed <family> <workspace> is the whole host-side seed step: generate
# the credentials into the workspace, emit the NoCloud data and pack it. It
# exports VM_SEED_ISO alongside the VM_SSH_KEY and VM_CREDS_ENV that
# generate_credentials exports, so it must be called directly — running it in a
# command substitution would confine every one of those exports to a subshell
# and leave the caller unable to reach the guest it just provisioned.
create_seed() {
    if [ "$#" -ne 2 ]; then
        cloudinit_fail "usage: create_seed <family> <workspace>"
    fi

    generate_credentials "$2"
    write_cloud_init_seed "$1" "$2"

    VM_SEED_ISO="$(build_seed_iso "$2")"
    export VM_SEED_ISO
    cloudinit_log "seed image $VM_SEED_ISO"
}
